services:
  - type: web
    name: chemfetch-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      # Supabase credentials - ADD THESE MANUALLY IN RENDER DASHBOARD
      # - key: SB_URL
      #   value: [ADD_IN_DASHBOARD]
      # - key: SB_SERVICE_KEY
      #   value: [ADD_IN_DASHBOARD]
      # OCR service URL (internal communication between services)
      - key: EXPO_PUBLIC_OCR_API_URL
        fromService:
          name: chemfetch-ocr-lightweight
          type: pserv
          property: host

  - type: pserv
    name: chemfetch-ocr-lightweight
    env: python
    # Simplified build command - prefer binary but allow fallback
    buildCommand: |
      cd ocr_service && 
      pip install --upgrade pip &&
      pip install --prefer-binary --no-cache-dir -r requirements.txt
    startCommand: cd ocr_service && gunicorn ocr_service:app --workers=1 --threads=2 --timeout=120 --preload=false -b 0.0.0.0:5001
    plan: free # Now fits within 512MB limit!
    envVars:
      - key: PORT
        value: 5001
      - key: OCR_MODE
        value: text-only
      - key: PYTHONUNBUFFERED
        value: '1'
      - key: DEBUG_IMAGES
        value: '0'
      # Build optimization environment variables
      - key: PIP_NO_CACHE_DIR
        value: '1'
      - key: PIP_PREFER_BINARY
        value: '1'

