services:
  - type: web
    name: chemfetch-backend
    env: node
    buildCommand: npm install && npm run build 
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      # Supabase credentials - ADD THESE MANUALLY IN RENDER DASHBOARD
      # - key: SB_URL
      #   value: [ADD_IN_DASHBOARD]
      # - key: SB_SERVICE_KEY
      #   value: [ADD_IN_DASHBOARD]
      # Google Search API credentials - ADD THESE MANUALLY IN RENDER DASHBOARD
      # - key: GOOGLE_SEARCH_API_KEY
      #   value: [ADD_IN_DASHBOARD]
      # - key: GOOGLE_SEARCH_ENGINE_ID
      #   value: [ADD_IN_DASHBOARD]
      # Frontend URLs for CORS
      - key: FRONTEND_URL
        value: https://chemfetch.com,https://chemfetch-client-hub-live.vercel.app
      # OCR service URL (internal communication between services)
      - key: EXPO_PUBLIC_OCR_API_URL
        fromService:
          name: chemfetch-ocr-lightweight
          type: pserv
          property: host

  - type: pserv
    name: chemfetch-ocr-lightweight
    env: python
    # Build command - prefer binary but allow fallback
    buildCommand: |
      cd ocr_service && 
      pip install --upgrade pip &&
      pip install --prefer-binary --no-cache-dir -r requirements.txt
    # IMPORTANT: Use python script directly since Render isn't respecting Gunicorn command
    startCommand: cd ocr_service && python ocr_service.py
    plan: free
    envVars:
      - key: PORT
        value: 5001
      - key: OCR_MODE
        value: text-only
      - key: PYTHONUNBUFFERED
        value: '1'
      - key: DEBUG_IMAGES
        value: '0'
      # Build optimization environment variables
      - key: PIP_NO_CACHE_DIR
        value: '1'
      - key: PIP_PREFER_BINARY
        value: '1'

