# chemfetch-backend-live/render.yaml
services:
  - type: web
    name: chemfetch-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      # OCR service URL - FIXED to use proper service name
      - key: EXPO_PUBLIC_OCR_API_URL
        fromService:
          name: chemfetch-ocr-lightweight
          type: pserv
          property: host
      # Alternative backup URL
      - key: OCR_SERVICE_URL
        fromService:
          name: chemfetch-ocr-lightweight
          type: pserv
          property: host

  - type: pserv
    name: chemfetch-ocr-lightweight
    env: python
    buildCommand: |
      cd ocr_service && 
      pip install --upgrade pip &&
      pip install --prefer-binary --no-cache-dir -r requirements.txt
    startCommand: cd ocr_service && python ocr_service.py
    plan: free
    envVars:
      - key: PORT
        value: 5001
      - key: OCR_MODE
        value: text-only
      - key: PYTHONUNBUFFERED
        value: '1'