services:
  - type: web
    name: chemfetch-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: OCR_SERVICE_URL
        fromService:
          name: chemfetch-ocr
          type: pserv
          property: host

  - type: pserv
    name: chemfetch-ocr
    env: python
    buildCommand: cd ocr_service && pip install -r requirements.txt
    startCommand: cd ocr_service && python ocr_service.py
    envVars:
      - key: PORT
        value: 5001
    disk:
      name: ocr-storage
      mountPath: /app/debug_images
      sizeGB: 1
